name: Dice App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout

      - name: Install Flutter
        uses: subosito/flutter-action@v3
